export const LANGUAGE = {
  locale: 'ja',
  wd: {
    appTitle: 'ArrivalAlerm',
    update: '更新',
    decision: '決定',
    del: '削除',
    distanceMessage1: '残り',
    distanceMessage2: 'で通知します',
    distanceMessageNone: '通知しません',
    getLocation: '位置情報取得',
    getLocationInterval: '位置情報取得間隔',
    getLocationDesAuto: '登録地点に従って自動で設定します',
    getLocationDesChoice:
      '高いほど位置情報が正確になりますが、\n消費電力もあがります',
    auto: '自動',
    choice: '指定',
    other: 'その他',
    pay: '120円',
    payDes: '有料版を購入\n・地点登録数が8個まで登録可能\n・通知距離を手動入力可能',
    initialize: '初期化',
    initializeQuestion: '初期化します、よろしいですか？',
    initializeOK: '初期化しました',
    initializeDes: '設定情報と登録地点を初期化',
    editTitle: 'タイトル',
    editAlermDistance: '通知距離',
    meter: 'メートル',
    editChoiceInput: '選択入力',
    editManualInput: '手動入力',
    editAlermWeekDay: '通知曜日',
    editChoiceWeekDay: '曜日を指定',
    monday: '月',
    tuesday: '火',
    wednesday: '水',
    thursday: '木',
    friday: '金',
    saturday: '土',
    sunday: '日',
    lowest: '最低',
    low: '低',
    balanced: '標準',
    high: '高',
    highest: '最高',
    best: 'MAX',
    editAlermTimeZone: '通知時間帯',
    start: '開始',
    end: '終了',
    editAlermTimeChoice: '時間を指定',
    alermPoint: '通知地点',
    arrivedNear: '付近に到着しました',
    freeAlert1: '無料版は',
    freeAlert2: '件までしか登録できません。',
  },
};
